### ISSUE TITLE
Import "home" section fails due its url

### ISSUE THREAD

**Issue by ChidVanid** [Pennebaker/craftcms-thearchitect#53]
Hi,

when I'm importing the architect json I always get an error because of the url of my homepage.
While exporting the plugin is generating "__home__" as url format in one of my sections. Even if I delete everything in a clean craft installation it always says, that the url format is already used. Or am I simply doing anything wrong?

```
{
  "name": "Startseite",
  "handle": "homepage",
  "type": "single",
  "enableVersioning": "1",
  "typesettings": {
    "template": "index",
    "urlFormat": "__home__",
    "nestedUrlFormat": null
  }
}
```

Craft CMS 2.6.2985
MAMP
thearchitect v1.6.0-beta.5 (because of the neo issue)

Thanks in advance.

**Comment by Emkaytoo** [comment]
@spAnser My only thoughts on this are that it might be a db thing because of how Craft stores & manages singles.

@ChidVanid This is a stupid question, but when you delete the home page and reimport it, is it not showing up in the entries section? I've used the Architect to overwrite the home page with a new entryType instead of replacing it entirely (because home is home), so I haven't experienced this error.

**Comment by ChidVanid** [comment]
A valid question, unfortunately it's not. I looked in the database. Now I think its whether a Craft issue or an issue with some of our installations. Even if I delete my entry with "__home__" it still show's up in the "elements_i18n" table. That's where the service is searching for matching routes.

Sorry for stealing your time I think the issue can be closed. Thanks
